# Generated by Django 4.2 on 2025-05-15 07:22

import core.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Bed",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("bed_number", models.CharField(max_length=10)),
                ("is_available", models.BooleanField(default=True)),
                ("admission_date", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="EmergencyCase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "case_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("RESOLVED", "Resolved"),
                            ("TRANSFERRED", "Transferred"),
                        ],
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                ("description", models.TextField()),
                (
                    "priority",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ]
                    ),
                ),
                ("admission_time", models.DateTimeField()),
                ("resolution_time", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="EmergencyTeam",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100)),
                ("specialization", models.CharField(max_length=100)),
                ("is_available", models.BooleanField(default=True)),
                ("contact_number", models.CharField(max_length=15)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="HospitalPolicy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("category", models.CharField(max_length=100)),
                ("is_active", models.BooleanField(default=True)),
                ("last_reviewed", models.DateField()),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="InventoryItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("MEDICINE", "Medicine"),
                            ("EQUIPMENT", "Equipment"),
                            ("SUPPLIES", "Supplies"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField()),
                ("quantity", models.IntegerField()),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("supplier", models.CharField(max_length=200)),
                ("expiry_date", models.DateField(blank=True, null=True)),
                ("reorder_level", models.IntegerField()),
                ("location", models.CharField(max_length=100)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="LabTest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "test_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("test_name", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("IN_PROGRESS", "In Progress"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("results", models.TextField(blank=True)),
                ("test_date", models.DateField()),
                ("result_date", models.DateField(blank=True, null=True)),
                ("is_urgent", models.BooleanField(default=False)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=200)),
                ("message", models.TextField()),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("APPOINTMENT", "Appointment"),
                            ("BILL", "Bill"),
                            ("EMERGENCY", "Emergency"),
                            ("SYSTEM", "System"),
                        ],
                        max_length=20,
                    ),
                ),
                ("is_read", models.BooleanField(default=False)),
                ("related_object_id", models.UUIDField(blank=True, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("room_number", models.CharField(max_length=10, unique=True)),
                (
                    "room_type",
                    models.CharField(
                        choices=[
                            ("GENERAL", "General Ward"),
                            ("PRIVATE", "Private Room"),
                            ("SEMI_PRIVATE", "Semi-Private Room"),
                            ("ICU", "Intensive Care Unit"),
                            ("OPERATION", "Operation Theater"),
                        ],
                        max_length=20,
                    ),
                ),
                ("capacity", models.IntegerField()),
                ("price_per_day", models.DecimalField(decimal_places=2, max_digits=10)),
                ("is_available", models.BooleanField(default=True)),
                ("floor", models.IntegerField()),
                ("wing", models.CharField(max_length=10)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AlterModelOptions(
            name="bill",
            options={},
        ),
        migrations.RemoveIndex(
            model_name="bill",
            name="core_bill_payment_b26b04_idx",
        ),
        migrations.RemoveIndex(
            model_name="bill",
            name="core_bill_due_dat_69b74b_idx",
        ),
        migrations.RemoveField(
            model_name="bill",
            name="appointment",
        ),
        migrations.AddField(
            model_name="appointment",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_appointments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="bill",
            name="bill_id",
            field=models.UUIDField(editable=False, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="bill",
            name="insurance_claim",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="bill",
            name="insurance_details",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="doctor",
            name="consultation_fee",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name="doctor",
            name="emergency_contact",
            field=models.CharField(default="", max_length=15),
        ),
        migrations.AddField(
            model_name="doctor",
            name="max_patients_per_day",
            field=models.IntegerField(default=20),
        ),
        migrations.AddField(
            model_name="doctor",
            name="qualification",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="employee",
            name="department",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="employee",
            name="emergency_contact",
            field=models.CharField(default="", max_length=15),
        ),
        migrations.AddField(
            model_name="employee",
            name="shift",
            field=models.CharField(
                choices=[
                    ("MORNING", "Morning"),
                    ("AFTERNOON", "Afternoon"),
                    ("NIGHT", "Night"),
                ],
                default="MORNING",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="medicalrecord",
            name="is_confidential",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="patient",
            name="admission_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="patient",
            name="bed_number",
            field=models.CharField(blank=True, default="", max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="patient",
            name="discharge_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="patient",
            name="gender",
            field=models.CharField(
                choices=[("MALE", "Male"), ("FEMALE", "Female"), ("OTHER", "Other")],
                default="OTHER",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="is_admitted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="patient",
            name="medical_history",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="patient",
            name="room_number",
            field=models.CharField(blank=True, default="", max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="status",
            field=models.CharField(
                choices=[
                    ("SCHEDULED", "Scheduled"),
                    ("COMPLETED", "Completed"),
                    ("CANCELLED", "Cancelled"),
                    ("NO_SHOW", "No Show"),
                ],
                default="SCHEDULED",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="bill",
            name="payment_method",
            field=models.CharField(
                blank=True,
                choices=[
                    ("CASH", "Cash"),
                    ("CARD", "Card"),
                    ("INSURANCE", "Insurance"),
                    ("ONLINE", "Online"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="bill",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("PAID", "Paid"),
                    ("OVERDUE", "Overdue"),
                    ("CANCELLED", "Cancelled"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="doctor",
            name="address",
            field=models.TextField(default=""),
        ),
        migrations.AlterField(
            model_name="doctor",
            name="experience",
            field=models.IntegerField(
                default=0,
                help_text="Years of experience (0-50)",
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(50),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="doctor",
            name="phone",
            field=models.CharField(
                default="",
                help_text="Enter a valid phone number",
                max_length=15,
                validators=[core.models.validate_phone_number],
            ),
        ),
        migrations.AlterField(
            model_name="doctor",
            name="specialization",
            field=models.CharField(
                choices=[
                    ("GENERAL", "General Physician"),
                    ("CARDIOLOGY", "Cardiology"),
                    ("NEUROLOGY", "Neurology"),
                    ("PEDIATRICS", "Pediatrics"),
                    ("DERMATOLOGY", "Dermatology"),
                    ("ORTHOPEDICS", "Orthopedics"),
                    ("GYNECOLOGY", "Gynecology"),
                    ("OPHTHALMOLOGY", "Ophthalmology"),
                    ("DENTISTRY", "Dentistry"),
                ],
                default="GENERAL",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="address",
            field=models.TextField(default=""),
        ),
        migrations.AlterField(
            model_name="employee",
            name="phone",
            field=models.CharField(
                default="",
                help_text="Enter a valid phone number",
                max_length=15,
                validators=[core.models.validate_phone_number],
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="position",
            field=models.CharField(
                choices=[
                    ("RECEPTIONIST", "Receptionist"),
                    ("NURSE", "Nurse"),
                    ("PHARMACIST", "Pharmacist"),
                    ("TECHNICIAN", "Lab Technician"),
                    ("ADMIN", "Administrator"),
                ],
                default="RECEPTIONIST",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="medicalrecord",
            name="notes",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="patient",
            name="address",
            field=models.TextField(default=""),
        ),
        migrations.AlterField(
            model_name="patient",
            name="blood_group",
            field=models.CharField(
                choices=[
                    ("A+", "A+"),
                    ("A-", "A-"),
                    ("B+", "B+"),
                    ("B-", "B-"),
                    ("AB+", "AB+"),
                    ("AB-", "AB-"),
                    ("O+", "O+"),
                    ("O-", "O-"),
                ],
                default="A+",
                max_length=5,
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="date_of_birth",
            field=models.DateField(
                blank=True, help_text="Format: YYYY-MM-DD", null=True
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="emergency_contact",
            field=models.CharField(
                default="",
                help_text="Emergency contact phone number",
                max_length=15,
                validators=[core.models.validate_phone_number],
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="emergency_contact_name",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="patient",
            name="phone",
            field=models.CharField(
                default="",
                help_text="Enter a valid phone number",
                max_length=15,
                validators=[core.models.validate_phone_number],
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="labtest",
            name="doctor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.doctor"
            ),
        ),
        migrations.AddField(
            model_name="labtest",
            name="patient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.patient"
            ),
        ),
        migrations.AddField(
            model_name="labtest",
            name="technician",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.employee",
            ),
        ),
        migrations.AddField(
            model_name="hospitalpolicy",
            name="reviewed_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="emergencyteam",
            name="leader",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.doctor",
            ),
        ),
        migrations.AddField(
            model_name="emergencyteam",
            name="members",
            field=models.ManyToManyField(to="core.employee"),
        ),
        migrations.AddField(
            model_name="emergencycase",
            name="patient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.patient"
            ),
        ),
        migrations.AddField(
            model_name="emergencycase",
            name="team",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.emergencyteam",
            ),
        ),
        migrations.AddField(
            model_name="bed",
            name="patient",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.patient",
            ),
        ),
        migrations.AddField(
            model_name="bed",
            name="room",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.room"
            ),
        ),
    ]
